#oops concept
#defining class and objects
class Myclass:
    def add(a,b):
        return a+b
    def sub(a,b):
        return a-b
    def mul(a,b):
        return a*b
    def div(a,b):
        return a/b
    def mod(a,b):
        return a%b
    
obj1=Myclass
obj2=Myclass
obj3=Myclass
obj4=Myclass
obj5=Myclass
print(obj1.add(2,5))
print(obj2.sub(2,5))
print(obj3.mul(2,5))
print(obj4.div(2,5))
print(obj5.mod(2,5))
    
