# WRITE A PROGRAM TO FIND AREA OF A CIRCLE
r=int(input())
A=(3.14*r*r)
print(A)
# WRITE A PROGRAM TO FIND A PERIMETER OF A CIRCLR
r=int(input())
C=(2*3.14*r)
print(C)
# WRITE A PROGRAM TO FIND AREA OF A TRIANGLE
b=int(input())
h=int(input())
A=(1/2*b*h)
print(A)
#WRITE A PROGRAM TO FIND A PERIMETER OF A TRIANGLE
side_a=int(input())
base_b=int(input())
side_c=int(input())
P=(side_a+base_b+side_c)
print(P)