#ACCESS THE ELEMENTS IN ASCII VALUES SUM OF DIGITS IN ASCII VALUE
#inp=input()
#sum=0
#for i in inp:
 #   if(ord(i)>=48 and ord(i)<=57):          #sum=0+1
  #    sum+=int(i)                            #sum=1+2=3->3+3=6
#print(sum)    
#write a code to print all the capital letters in the given string
inp=input()
for i in inp:
    if(ord(i)>=68 and ord(i)<=93):                           #sum=1+2=3->3+3=6
        print(i)    